### ISSUE TITLE
how do I add accounts? What is the format for the files?

### ISSUE THREAD

**Issue by maximilianspitzer** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#1]

**Comment by farshadz1997** [comment]
You can import your accounts file if you had previous versions, or add your account through accounts tab in app

**Comment by maximilianspitzer** [comment]
When i try using the tab it just give me accounts file not exist

**Comment by maximilianspitzer** [comment]
`Exception in thread Thread-159 (handler):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 277, in pick_accounts_result
    self.look_for_log_in_accounts()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 391, in look_for_log_in_accounts
    self.accounts.append({"username": "your email", "password": "your password"})
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
Exception in thread Thread-188 (handler):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 277, in pick_accounts_result
    self.look_for_log_in_accounts()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 391, in look_for_log_in_accounts
    self.accounts.append({"username": "your email", "password": "your password"})
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
Exception in thread Thread-204 (clear_accounts_path):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 364, in clear_accounts_path
    self.page.session.remove("MRFarmer.accounts")
  File "/opt/homebrew/lib/python3.11/site-packages/flet/session_storage.py", line 19, in remove
    self.__store.pop(key)
KeyError: 'MRFarmer.accounts'
Exception in thread Thread-208 (clear_accounts_path):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 364, in clear_accounts_path
    self.page.session.remove("MRFarmer.accounts")
  File "/opt/homebrew/lib/python3.11/site-packages/flet/session_storage.py", line 19, in remove
    self.__store.pop(key)
KeyError: 'MRFarmer.accounts'
Exception in thread Thread-212 (clear_accounts_path):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 364, in clear_accounts_path
    self.page.session.remove("MRFarmer.accounts")
  File "/opt/homebrew/lib/python3.11/site-packages/flet/session_storage.py", line 19, in remove
    self.__store.pop(key)
KeyError: 'MRFarmer.accounts'
Exception in thread Thread-216 (clear_accounts_path):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 364, in clear_accounts_path
    self.page.session.remove("MRFarmer.accounts")
  File "/opt/homebrew/lib/python3.11/site-packages/flet/session_storage.py", line 19, in remove
    self.__store.pop(key)
KeyError: 'MRFarmer.accounts'
Exception in thread Thread-220 (clear_accounts_path):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 364, in clear_accounts_path
    self.page.session.remove("MRFarmer.accounts")
  File "/opt/homebrew/lib/python3.11/site-packages/flet/session_storage.py", line 19, in remove
    self.__store.pop(key)
KeyError: 'MRFarmer.accounts'
max@Maximilians-MBP Microsoft-Rewards-bot-GUI-V2-master % python3 main.pyw
Exception in thread Thread-140 (handler):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/flet/event_handler.py", line 16, in handler
    h(r)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 277, in pick_accounts_result
    self.look_for_log_in_accounts()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 391, in look_for_log_in_accounts
    self.accounts.append({"username": "your email", "password": "your password"})
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'`

**Comment by farshadz1997** [comment]
it created accounts.json file in directory, opent it from home tab, and from accounts tab add your accounts in it
