### ISSUE TITLE
On fresh install

### ISSUE THREAD

**Issue by maximilianspitzer** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#11]
`Unhandled error processing page session 4dff672e-8748-4e7a-b5bc-245b7acb586e: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/flet/flet.py", line 220, in on_session_created
    session_handler(page)
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/app_layout.py", line 41, in __init__
    self.ui()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/app_layout.py", line 86, in ui
    self.home_page = Home(self, self.page)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 18, in __init__
    self.set_initial_values()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 351, in set_initial_values
    self.look_for_log_in_accounts()
  File "/Users/max/Downloads/Microsoft-Rewards-bot-GUI-V2-master/src/ui/home.py", line 391, in look_for_log_in_accounts
    self.accounts.append({"username": "your email", "password": "your password"})
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'`

**Comment by farshadz1997** [comment]
you should not get this error, what is your OS? if you are on Linux check does app have permission to create file in directory?

**Comment by maximilianspitzer** [comment]
I'm on macOS

**Comment by farshadz1997** [comment]
Sorry I don't MacOS so I can't debug it on.

**Comment by farshadz1997** [comment]
Fixed in #69
