### ISSUE TITLE
Cant run it on Raspberry Pi

### ISSUE THREAD

**Issue by zumokuta** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#14]
I tried to use it on raspberry pi 3b but it gives this error ( Thanks In Advance ) : 

Traceback (most recent call last):
  File "/home/pi/Desktop/trial/Microsoft-Rewards-bot-GUI-V2/main.pyw", line 18, in <module>
    main()
  File "/home/pi/Desktop/trial/Microsoft-Rewards-bot-GUI-V2/main.pyw", line 14, in main
    ft.app(target=UserInterface)
  File "/home/pi/.local/lib/python3.9/site-packages/flet/flet.py", line 139, in app
    fvp = open_flet_view(conn.page_url, view == FLET_APP_HIDDEN)
  File "/home/pi/.local/lib/python3.9/site-packages/flet/flet.py", line 442, in open_flet_view
    tar_file = _download_flet_client(gz_filename)
  File "/home/pi/.local/lib/python3.9/site-packages/flet/flet.py", line 513, in _download_flet_client
    urllib.request.urlretrieve(flet_url, temp_arch)
  File "/usr/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by farshadz1997** [comment]
I don't think Flet framework works on Raspberry Pi

**Comment by zumokuta** [comment]
Oh okay so I tried using the GUI you first made with PyQt5 but it says no internet connection when i run it on pi.

**Comment by Prabh-Saini** [comment]
Hey,
Chrome doesn't have an official webdriver which is compatible with any model of raspberry pis. This is because they use an ARM processor. There are work arounds such as the following, and Flet only works on newer raspberry pi's (which i believe includes the 3b+). I'm personally not sure at the moment how to get it working but if you have the knowledge, this doesn't seem to be to hard to attempt to fix. 

`sudo apt-get install chromium-chromedriver`
```
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1600, 1200))
display.start()
driver = webdriver.Chrome('/usr/lib/chromium-browser/chromedriver')
```

**Comment by zumokuta** [comment]
i installed the command prompt but i dont know what to do with the phython snippet. Thanks in advance!
