### ISSUE TITLE
main.pyw wont open

### ISSUE THREAD

**Issue by Konrayy** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#29]
I ran everything I was supposed to and saved the webdriver in my windows folder but main.pyw still wont open, it only opens in notes. Not sure if I'm missing something or if I'm just a little slow

**Comment by farshadz1997** [comment]
why do you open it with notes? open terminal and type ```python main.pyw``` or run it with VScode or other text editors

**Comment by OwnerCM** [comment]
> why do you open it with notes? open terminal and type `python main.pyw` or run it with VScode or other text editors

Traceback (most recent call last):
  File "E:\BingRewards\Microsoft-Rewards-bot-GUI-V2\main.pyw", line 18, in <module>
    main()
  File "E:\BingRewards\Microsoft-Rewards-bot-GUI-V2\main.pyw", line 14, in main
    ft.app(target=UserInterface, assets_dir="assets")
  File "D:\Program Files\Python\Lib\site-packages\flet\flet.py", line 102, in app
    conn = _connect_internal(
           ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\flet\flet.py", line 264, in _connect_internal
    raise Exception(
Exception: Could not connected to Flet server in 30 seconds.
