### ISSUE TITLE
It shows this error when I click on start. I don't know what it is about, can you help ?!

### ISSUE THREAD

**Issue by abhaytomar05** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#35]
It shows this error when I click on start. I don't know what it is about, can you help ?!

Exception in thread Thread-189 (start):
Traceback (most recent call last):
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "e:\Codes\Python codes\autoBingwithgit\Microsoft-Rewards-bot-GUI-V2-master\Microsoft-Rewards-bot-GUI-V2-master\src\ui\home.py", line 453, in start
    self.farmer.perform_run()
  File "e:\Codes\Python codes\autoBingwithgit\Microsoft-Rewards-bot-GUI-V2-master\Microsoft-Rewards-bot-GUI-V2-master\src\core\farmer.py", line 1546, in perform_run
    self.get_or_create_logs()
  File "e:\Codes\Python codes\autoBingwithgit\Microsoft-Rewards-bot-GUI-V2-master\Microsoft-Rewards-bot-GUI-V2-master\src\core\farmer.py", line 214, in get_or_create_logs
    self.update_accounts()
  File "e:\Codes\Python codes\autoBingwithgit\Microsoft-Rewards-bot-GUI-V2-master\Microsoft-Rewards-bot-GUI-V2-master\src\core\farmer.py", line 224, in update_accounts
    self.parent.update_accounts_file()
  File "e:\Codes\Python codes\autoBingwithgit\Microsoft-Rewards-bot-GUI-V2-master\Microsoft-Rewards-bot-GUI-V2-master\src\ui\app_layout.py", line 247, in update_accounts_file
    with open(self.page.client_storage.get("MRFarmer.accounts_path"), "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'E:\\Codes\\Python codes\\autoBingwithgit\\Microsoft-Rewards-bot-GUI-V2-master\\Microsoft-Rewards-bot-GUI-V2-master\\accounts.json'

**Comment by farshadz1997** [comment]
app doesn't have permission to write on files, give it permissions that it required.
